spring:
  datasource:
    username: root
    password: "0503"
    url: jdbc:mysql://106.52.78.230:3306/Order_food?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  data:

    redis:

      host: 106.52.78.230        # Redis服务器主机名，默认为localhost
      port: 6379             # Redis服务器端口，默认为6379
      password: ""             # Redis服务器密码（如果有的话）
      database: 0            # Redis数据库索引，默认为0
      lettuce:
        pool:
          max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-idle: 8    # 连接池中的最大空闲连接 默认 8
          min-idle: 0    # 连接池中的最小空闲连接 默认 0

  cache:
    type: redis
    redis:
      time-to-live: 86400000
      cache-null-values: true

  security:
    user:
      name: yowayimono
      password: "0503"


ip: localhost
server:
  port: 8000

springdoc:
  swagger-ui:
    path: /swagger-ui.html




File:
  uploadPath: ${BASE_LOCATION}\upload\tmp