spring:
  datasource:
    username: root
    password: "0503"
    url: jdbc:mysql://106.52.78.230:3306/order_food?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      port: 6379
      password: ""
      database: 0
      host: 106.52.78.230
  security:
    user:
      name: yowayimono
      password: "0503"


minjwt:
  secret: "0503qwm"
  expiration: 3600L
  refresh-token:
    expiration: 3600L*24



springdoc:
  swagger-ui:
    path: /swagger-ui.html




