spring:
  datasource:
    username: root
    password: "0503"
    url: jdbc:mysql://106.52.78.230:3306/java_demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 106.52.78.230        # Redis服务器主机名，默认为localhost
      port: 6379             # Redis服务器端口，默认为6379
      password: ""             # Redis服务器密码（如果有的话）
      database: 0            # Redis数据库索引，默认为0


  security:
    user:
      name: yowayimono
      password: "0503"





springdoc:
  swagger-ui:
    path: /swagger-ui.html




File:
  uploadPath: ${BASE_LOCATION}\upload\tmp